-- Forge schema (SQLite): one person's projects, their repos, servers and
-- endpoints, the tasks on them, the agent runs dispatched to machines, the
-- vault, check-ups and the security log.
--
-- Conventions, relied on by internal/db and internal/store:
--   timestamps  TEXT, UTC, "YYYY-MM-DDTHH:MM:SS.sssZ" — fixed width, so text
--               comparison is time order. now() (registered by internal/db)
--               and the DEFAULT below write exactly this.
--   dates       TEXT "YYYY-MM-DD".
--   lists/JSON  TEXT holding JSON (tags, labels, links, capabilities…).
--   booleans    INTEGER 0/1.
--   CHECKs      named <table>_<column>_check, so a violation names its field.

CREATE TABLE users (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    username            TEXT NOT NULL,
    email               TEXT NOT NULL,
    display_name        TEXT NOT NULL DEFAULT '',
    password_hash       TEXT NOT NULL,
    -- the current password was generated by Forge (create-user,
    -- reset-password on the command line), not chosen: the check-up nags
    password_generated  INTEGER NOT NULL DEFAULT 0,
    timezone            TEXT NOT NULL DEFAULT 'UTC',
    weekly_goal         INTEGER NOT NULL DEFAULT 10 CONSTRAINT users_weekly_goal_check CHECK (weekly_goal BETWEEN 1 AND 500),
    accent              TEXT NOT NULL DEFAULT '',
    totp_enabled        INTEGER NOT NULL DEFAULT 0,
    totp_secret         BLOB,              -- sealed with the vault key
    totp_pending        BLOB,              -- set up but not yet confirmed
    totp_last_counter   INTEGER NOT NULL DEFAULT 0,  -- a code works once
    checkup_time        TEXT NOT NULL DEFAULT '07:30'
                        CONSTRAINT users_checkup_time_check CHECK (checkup_time GLOB '[0-2][0-9]:[0-5][0-9]' AND checkup_time < '24:00'),
    checkup_email       INTEGER NOT NULL DEFAULT 1,
    password_changed_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE UNIQUE INDEX users_username_key ON users (lower(username));
CREATE UNIQUE INDEX users_email_key ON users (lower(email));

-- Only a SHA-256 of the cookie value is stored: a leaked table is not a set
-- of live sessions.
CREATE TABLE sessions (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id        INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash     BLOB NOT NULL UNIQUE,
    user_agent     TEXT NOT NULL DEFAULT '',
    ip             TEXT NOT NULL DEFAULT '',
    created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    last_seen_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    expires_at     TEXT NOT NULL,
    -- step-up: the password re-entered recently, on this session only
    elevated_until TEXT
);
CREATE INDEX sessions_user_idx ON sessions (user_id);

CREATE TABLE password_resets (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id    INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash BLOB NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    used_at    TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE projects (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    key              TEXT NOT NULL UNIQUE CONSTRAINT projects_key_check
                     CHECK (length(key) BETWEEN 2 AND 10 AND key GLOB '[A-Z]*' AND key NOT GLOB '*[^A-Z0-9]*'),
    name             TEXT NOT NULL CONSTRAINT projects_name_check CHECK (name <> ''),
    category         TEXT NOT NULL DEFAULT 'personal' CONSTRAINT projects_category_check CHECK (category IN ('work', 'personal')),
    status           TEXT NOT NULL DEFAULT 'building'
                     CONSTRAINT projects_status_check CHECK (status IN ('live', 'building', 'radar', 'paused', 'archived')),
    priority         INTEGER NOT NULL DEFAULT 3 CONSTRAINT projects_priority_check CHECK (priority BETWEEN 1 AND 5),
    color            TEXT NOT NULL DEFAULT '#6366f1'
                     CONSTRAINT projects_color_check CHECK (color GLOB '#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]'),
    summary          TEXT NOT NULL DEFAULT '',
    description      TEXT NOT NULL DEFAULT '',
    infra_notes      TEXT NOT NULL DEFAULT '',
    target_date      TEXT,
    links            TEXT NOT NULL DEFAULT '[]',
    next_task_number INTEGER NOT NULL DEFAULT 1,
    created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- `git` is the latest scan the master reported (GitStatus in docs/API.md).
-- A snapshot, not history: the dashboard wants "now".
CREATE TABLE repos (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id     INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    name           TEXT NOT NULL CONSTRAINT repos_name_check CHECK (name <> ''),
    path           TEXT NOT NULL DEFAULT '',
    remote_url     TEXT NOT NULL DEFAULT '',
    default_branch TEXT NOT NULL DEFAULT 'main',
    kind           TEXT NOT NULL DEFAULT 'other'
                   CONSTRAINT repos_kind_check CHECK (kind IN ('api', 'ui', 'mobile', 'infra', 'lib', 'site', 'other')),
    deploy         TEXT NOT NULL DEFAULT '',
    notes          TEXT NOT NULL DEFAULT '',
    sort_order     INTEGER NOT NULL DEFAULT 0,
    git            TEXT,
    created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (project_id, name)
);

CREATE TABLE servers (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    name           TEXT NOT NULL UNIQUE CONSTRAINT servers_name_check CHECK (name <> ''),
    role           TEXT NOT NULL DEFAULT '',
    provider       TEXT NOT NULL DEFAULT '',
    arch           TEXT NOT NULL DEFAULT '',
    public_address TEXT NOT NULL DEFAULT '',
    tailscale_ip   TEXT NOT NULL DEFAULT '',
    environment    TEXT NOT NULL DEFAULT 'production'
                   CONSTRAINT servers_environment_check CHECK (environment IN ('production', 'staging', 'dev', 'infra')),
    critical       INTEGER NOT NULL DEFAULT 0,
    tags           TEXT NOT NULL DEFAULT '[]',
    notes          TEXT NOT NULL DEFAULT '',
    created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE project_servers (
    project_id INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    server_id  INTEGER NOT NULL REFERENCES servers (id) ON DELETE CASCADE,
    role       TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (project_id, server_id)
);

CREATE TABLE endpoints (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id      INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    name            TEXT NOT NULL CONSTRAINT endpoints_name_check CHECK (name <> ''),
    url             TEXT NOT NULL CONSTRAINT endpoints_url_check CHECK (url GLOB 'http://?*' OR url GLOB 'https://?*'),
    kind            TEXT NOT NULL DEFAULT 'web' CONSTRAINT endpoints_kind_check CHECK (kind IN ('web', 'api', 'health')),
    expect_status   INTEGER NOT NULL DEFAULT 200 CONSTRAINT endpoints_expect_status_check CHECK (expect_status BETWEEN 100 AND 599),
    enabled         INTEGER NOT NULL DEFAULT 1,
    last_status     TEXT NOT NULL DEFAULT 'unknown' CONSTRAINT endpoints_last_status_check CHECK (last_status IN ('up', 'down', 'unknown')),
    last_code       INTEGER,
    last_latency_ms INTEGER,
    last_error      TEXT NOT NULL DEFAULT '',
    last_checked_at TEXT,
    last_change_at  TEXT,
    created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE endpoint_checks (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    endpoint_id INTEGER NOT NULL REFERENCES endpoints (id) ON DELETE CASCADE,
    at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    ok          INTEGER NOT NULL,
    code        INTEGER,
    latency_ms  INTEGER,
    error       TEXT NOT NULL DEFAULT ''
);
CREATE INDEX endpoint_checks_endpoint_at_idx ON endpoint_checks (endpoint_id, at DESC);

CREATE TABLE tasks (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id   INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    number       INTEGER NOT NULL,
    title        TEXT NOT NULL CONSTRAINT tasks_title_check CHECK (title <> ''),
    description  TEXT NOT NULL DEFAULT '',
    status       TEXT NOT NULL DEFAULT 'todo'
                 CONSTRAINT tasks_status_check CHECK (status IN ('backlog', 'todo', 'in_progress', 'blocked', 'done')),
    priority     TEXT NOT NULL DEFAULT 'medium' CONSTRAINT tasks_priority_check CHECK (priority IN ('urgent', 'high', 'medium', 'low')),
    type         TEXT NOT NULL DEFAULT 'feature'
                 CONSTRAINT tasks_type_check CHECK (type IN ('feature', 'bug', 'chore', 'research', 'ops')),
    labels       TEXT NOT NULL DEFAULT '[]',
    due_date     TEXT,
    focus        INTEGER NOT NULL DEFAULT 0,
    repo_id      INTEGER REFERENCES repos (id) ON DELETE SET NULL,
    estimate     INTEGER CONSTRAINT tasks_estimate_check CHECK (estimate IS NULL OR estimate BETWEEN 0 AND 1000),
    sort_order   REAL NOT NULL DEFAULT 0,
    completed_at TEXT,
    created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (project_id, number)
);
CREATE INDEX tasks_project_status_idx ON tasks (project_id, status, sort_order);
CREATE INDEX tasks_completed_idx ON tasks (completed_at) WHERE completed_at IS NOT NULL;

CREATE TABLE comments (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    task_id    INTEGER NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
    body       TEXT NOT NULL CONSTRAINT comments_body_check CHECK (body <> ''),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX comments_task_idx ON comments (task_id);

-- A machine running `forge agent`. One master (always on, runs everything,
-- the only source of repo state), an iOS machine (a Mac for Xcode builds),
-- workers for the rest.
CREATE TABLE runners (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    name            TEXT NOT NULL UNIQUE CONSTRAINT runners_name_check CHECK (name <> ''),
    token_hash      BLOB NOT NULL UNIQUE,
    role            TEXT NOT NULL DEFAULT 'worker' CONSTRAINT runners_role_check CHECK (role IN ('master', 'ios', 'worker')),
    hostname        TEXT NOT NULL DEFAULT '',
    os              TEXT NOT NULL DEFAULT '',
    version         TEXT NOT NULL DEFAULT '',
    capabilities    TEXT NOT NULL DEFAULT '{}',
    tmux            TEXT NOT NULL DEFAULT '[]',   -- tmux sessions as of the last heartbeat
    tmux_at         TEXT,
    -- pairing: `forge agent pair <url> <code>` swaps this one-time code for
    -- the token; only its hash is kept, and only until it expires
    pair_code_hash  BLOB,
    pair_expires_at TEXT,
    last_seen_at    TEXT,
    created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE UNIQUE INDEX runners_one_master ON runners (role) WHERE role = 'master';
CREATE UNIQUE INDEX runners_pair_code_idx ON runners (pair_code_hash) WHERE pair_code_hash IS NOT NULL;

CREATE TABLE runs (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    runner_id        INTEGER REFERENCES runners (id) ON DELETE SET NULL,
    runner_name      TEXT NOT NULL DEFAULT '',
    project_id       INTEGER NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    repo_id          INTEGER NOT NULL REFERENCES repos (id) ON DELETE CASCADE,
    task_id          INTEGER REFERENCES tasks (id) ON DELETE SET NULL,
    kind             TEXT NOT NULL CONSTRAINT runs_kind_check CHECK (kind IN ('agent', 'command')),
    prompt           TEXT NOT NULL DEFAULT '',
    command          TEXT NOT NULL DEFAULT '',
    permission_mode  TEXT NOT NULL DEFAULT '',
    model            TEXT NOT NULL DEFAULT '',
    worktree         INTEGER NOT NULL DEFAULT 0,
    resume_run_id    INTEGER REFERENCES runs (id) ON DELETE SET NULL,
    resume_session   TEXT NOT NULL DEFAULT '',
    status           TEXT NOT NULL DEFAULT 'queued'
                     CONSTRAINT runs_status_check CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
    cancel_requested INTEGER NOT NULL DEFAULT 0,
    session_id       TEXT NOT NULL DEFAULT '',
    result           TEXT NOT NULL DEFAULT '',
    error            TEXT NOT NULL DEFAULT '',
    exit_code        INTEGER,
    cost_usd         REAL,
    num_turns        INTEGER,
    duration_ms      INTEGER,
    event_seq        INTEGER NOT NULL DEFAULT 0,
    created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    started_at       TEXT,
    finished_at      TEXT
);
CREATE INDEX runs_runner_status_idx ON runs (runner_id, status);
CREATE INDEX runs_project_idx ON runs (project_id, created_at DESC);

CREATE TABLE run_events (
    run_id INTEGER NOT NULL REFERENCES runs (id) ON DELETE CASCADE,
    seq    INTEGER NOT NULL,
    at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    kind   TEXT NOT NULL CONSTRAINT run_events_kind_check CHECK (kind IN ('claude', 'stdout', 'stderr', 'system')),
    data   TEXT NOT NULL,
    PRIMARY KEY (run_id, seq)
);

-- The feed. task_ref is a snapshot so history still reads after a task is
-- deleted or moved to another project.
CREATE TABLE activity (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    project_id INTEGER REFERENCES projects (id) ON DELETE CASCADE,
    task_id    INTEGER REFERENCES tasks (id) ON DELETE SET NULL,
    task_ref   TEXT,
    run_id     INTEGER REFERENCES runs (id) ON DELETE SET NULL,
    kind       TEXT NOT NULL,
    summary    TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX activity_created_idx ON activity (created_at DESC);
CREATE INDEX activity_project_idx ON activity (project_id, created_at DESC);

-- Secrets and files, sealed with AES-256-GCM under a key that is NOT in this
-- database (vault.key in the workspace). Everything outside secret_sealed /
-- file_sealed is metadata and is returned by list endpoints; `aad` binds each
-- ciphertext to its row so sealed blobs cannot be swapped between items.
CREATE TABLE vault_items (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    aad              BLOB NOT NULL,
    name             TEXT NOT NULL CONSTRAINT vault_items_name_check CHECK (name <> ''),
    kind             TEXT NOT NULL CONSTRAINT vault_items_kind_check CHECK (kind IN ('password', 'api_key', 'private_key', 'keystore',
                         'certificate', 'provisioning_profile', 'service_account', 'token', 'env_file', 'note', 'reference')),
    project_id       INTEGER REFERENCES projects (id) ON DELETE SET NULL,
    platform         TEXT NOT NULL DEFAULT '',
    host             TEXT NOT NULL DEFAULT '',
    identifier       TEXT NOT NULL DEFAULT '',
    fields           TEXT NOT NULL DEFAULT '{}',
    secret_keys      TEXT NOT NULL DEFAULT '[]',
    secret_sealed    BLOB,
    file_name        TEXT NOT NULL DEFAULT '',
    file_size        INTEGER NOT NULL DEFAULT 0,
    file_sealed      BLOB,
    location         TEXT NOT NULL DEFAULT '',
    expires_at       TEXT,
    notes            TEXT NOT NULL DEFAULT '',
    tags             TEXT NOT NULL DEFAULT '[]',
    created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    last_revealed_at TEXT
);
CREATE INDEX vault_items_project_idx ON vault_items (project_id);

CREATE TABLE vault_audit (
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    item_id   INTEGER REFERENCES vault_items (id) ON DELETE SET NULL,
    item_name TEXT NOT NULL,
    action    TEXT NOT NULL CONSTRAINT vault_audit_action_check CHECK (action IN ('create', 'update', 'reveal', 'download', 'delete')),
    ip        TEXT NOT NULL DEFAULT '',
    at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX vault_audit_at_idx ON vault_audit (at DESC);

-- One row per check-up run. `items` is the whole result (CheckItem[] in
-- docs/API.md); done/task_id are edited in place as the day's actions get
-- ticked off, so the row is the action list.
CREATE TABLE checkups (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    date        TEXT NOT NULL,
    trigger     TEXT NOT NULL CONSTRAINT checkups_trigger_check CHECK (trigger IN ('schedule', 'manual')),
    started_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    finished_at TEXT,
    status      TEXT NOT NULL DEFAULT 'ok' CONSTRAINT checkups_status_check CHECK (status IN ('ok', 'warn', 'fail')),
    items       TEXT NOT NULL DEFAULT '[]',
    emailed     INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX checkups_date_idx ON checkups (date DESC, id DESC);

-- Security log: who signed in, from where, what sensitive thing they did.
-- Forge opens shells and hands out signing keys, so "what happened on my
-- account" has to be answerable from the app, not from container logs.
CREATE TABLE security_events (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    kind       TEXT NOT NULL,
    detail     TEXT NOT NULL DEFAULT '',
    ip         TEXT NOT NULL DEFAULT '',
    user_agent TEXT NOT NULL DEFAULT '',
    session_id INTEGER,
    at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX security_events_at_idx ON security_events (at DESC);
CREATE INDEX security_events_kind_at_idx ON security_events (kind, at DESC);

-- Login history survives the session row (deleted at logout), so a "new
-- device?" check has something to compare against.
CREATE TABLE known_devices (
    ip         TEXT NOT NULL,
    user_agent TEXT NOT NULL,
    first_seen TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    last_seen  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    PRIMARY KEY (ip, user_agent)
);
